### ISSUE TITLE
Package fails to install on OSX

### ISSUE THREAD

**Issue by kolanos** [iopipe/iopipe-plugin-profiler#27]
Following error occurs with `yarn add @iopipe/profiler`:

    error /Users/kolanos/Web/iopipe/iopipe-js-core/testProjects/extendConfig/node_modules/v8-profiler: Command failed.
    Exit code: 1
    Command: sh
    Arguments: -c node-pre-gyp install --fallback-to-build
    Directory: /Users/kolanos/Web/iopipe/iopipe-js-core/testProjects/extendConfig/node_modules/v8-profiler
    Output:
    node-pre-gyp info it worked if it ends with ok
    node-pre-gyp info using node-pre-gyp@0.6.39
    node-pre-gyp info using node@9.3.0 | darwin | x64
    node-pre-gyp info check checked for "/Users/kolanos/Web/iopipe/iopipe-js-core/testProjects/extendConfig/node_modules/v8-profiler/build/profiler/v5.7.0/node-v59-darwin-x64/profiler.node" (not found)
    node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v59-darwin-x64.tar.gz
    node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v59-darwin-x64.tar.gz
    node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v59-darwin-x64.tar.gz 
    node-pre-gyp ERR! Pre-built binaries not found for v8-profiler@5.7.0 and node@9.3.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp) 
    node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/profiler/v5.7.0/node-v59-darwin-x64.tar.gz 
    node-pre-gyp ERR! build error 
    node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/kolanos/Web/iopipe/iopipe-js-core/testProjects/extendConfig/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:389:16)
    node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:152:19)
    node-pre-gyp ERR! System Darwin 16.7.0
    node-pre-gyp ERR! command "/usr/local/Cellar/node/9.3.0_1/bin/node" "/Users/kolanos/Web/iopipe/iopipe-js-core/testProjects/extendConfig/node_modules/v8-profiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd /Users/kolanos/Web/iopipe/iopipe-js-core/testProjects/extendConfig/node_modules/v8-profiler
    node-pre-gyp ERR! node -v v9.3.0
    node-pre-gyp ERR! node-pre-gyp -v v0.6.39
    node-pre-gyp ERR! not ok 
    Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
    info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by ewindisch** [comment]
@kolanos it seems you don't have `node-gyp` installed. Maybe we need to add that as a dependency? Try installing it manually and seeing if that gets you further!
